###01 POST Create  Product
POST http://localhost:3000/products
Content-Type: application/x-www-form-urlencoded

name=Camara&
price=100

###02 POST Create  Product
POST http://localhost:3000/products
Content-Type: application/x-www-form-urlencoded

name=Laptop&
price=2300